### ISSUE TITLE
1

### ISSUE THREAD

**Issue by EkaterinaAlimpievaOwO** [GitDz3/gitDZ#1]
Создать  Маркдаун Файл с заголовком "Hello World!" в новой ветке

**Comment by ZulixDev** [comment]
Я НЕ ЧАСТЬ ГИКБРЕЙНС КУРСОВ, НО ЭТИ КУРСЫ ВСЕ РАВНО ДОБРАЛИСЬ ДО МЕНЯ

**Comment by ZulixDev** [comment]
ТИМЛИД, ЗАДАЧА ВЫПОЛНЕНА
